### PR TITLE
Added description of the remote protocol.

### PR DESCRIPTION
**Pull request by kukabu**
Hello

### CODE REVIEW

**Comment by csete** [comment]
Thanks, but have you seen the existing documentation on the website?
http://gqrx.dk/doc/remote-control

If something is missing there I will be happy to update, but I would really prefer to have the documentation at only one place to make maintenance as easy as possible. Otherwise we risk having out of date documents one place.

**Comment by kukabu** [comment]
Oh, I don't seen web documentation, but I think short description is need.
1. it's offline documentation.
2. it's can be included in binary packages for different distributions.

**Comment by csete** [comment]
If you change the format to plain text and move it to resources/remote-control.txt, we can include it in the program under the Help menu, just like the news.txt file.

**Comment by kukabu** [comment]
is it ok?

**Comment by csete** [comment]
Yes, it is fine, thanks you. I have now included it under the Help menu.

**Comment by kukabu** [comment]
Thanks!

**Pull request merged**
