### PR TITLE
Draw small negative frequencies correctly

### PR DESCRIPTION
**Pull request by Cat-Ion**
This would be a fix for #388. Having to check this in the drawing method's a bit ugly, but I think we'd have to change the digitinfo struct to use a separate sign and value otherwise.

### CODE REVIEW

**Comment by csete** [comment]
It doesn't seem to be working correctly.

1. Start with offset 0 Hz.
2. Step down with 100 Hz steps -> shown offset is positive
3. At -1 kHz the minus sign appears.
4. Step up with 100 Hz step -> minus sign is shown correctly
5. After you cross 0 Hz and offset becomes positive, the minus sign is still shown.

**Comment by Cat-Ion** [comment]
Oh, that must be because the 0 doesn't actually change, so it doesn't redraw it. I'll take a look, thanks.

**Comment by Cat-Ion** [comment]
How about this? :)

**Comment by csete** [comment]
It works now, thanks.

I merged it manually because I wanted to squash the commits into one commit. Keeping many intermediate commits makes sense when each individual commit is meaningful on its own. In this case all commits are necessary to fix the issue.

**Pull request closed without merging**
