### PR TITLE
Replace deprecated blocks::udp_sink with network::udp_sink.

### PR DESCRIPTION
**Pull request by willcode**
This is not a complete solution. The hostname and port are fixed
at make() to 127.0.0.1/7355 and can not be changed. The newer
udp_sink is not quite the same as the old one.

Signed-off-by: Jeff Long <willcode4@gmail.com>

### CODE REVIEW

**Comment by willcode** [comment]
This relates to recent changes on the gnuradio master branch, slated to become 3.10. Only people building gnuradio from source will be affected until 3.10 is released.

**Comment by ulrichloose** [comment]
until 3.10 is released?

Does that mean that deprecated blocks::udpsink is contained in 3.10 again, or is the "until" ambiguous and changes in gqrx are necessary from master beyond 3.10?

**Comment by willcode** [comment]
blocks::udp_sink has been removed. Currently, only people building from the gnuradio master branch will notice (GQRX will not build against the current gnuradio master). When 3.10 is released and starts showing up in distros, more people will notice the change.

Affinity of prepositions is not as well defined as affinity of operators in programming :-)

**Comment by ulrichloose** [comment]
Thanks for the clarification - English is not my mother tongue and so I was a little unsure how to interpret the statement.

I didn't want to appear precocious (;-)

**Comment by argilo** [comment]
I'm working on a complete fix over here: https://github.com/argilo/gqrx/tree/gr-network-udp-sink

One issue I ran into is that Homebrew's GNU Radio formula does not build the gr-network module. I've opened a PR to fix that: https://github.com/Homebrew/homebrew-core/pull/75940

**Comment by willcode** [comment]
Sounds good. I'll close this one but leave the branch in place for now.

**Pull request closed without merging**
