### PR TITLE
Adding Support for DX Cluster in GQRX

### PR DESCRIPTION
**Pull request by dh2wq**
Hi,
I would like to add DXCluster Support to my main use gqrx as panadapter.
I mainly reused the Bookmark feature and tried to implement no collision with the bookmark feature.
Fir Reference this is an screenshot of ongoing WAE Contest this weekend.

gqrc dxcluster wae
Following image is showing my settings to connect it to my local Skimmer Server instance. 
gqrx dxc options dh2wq skimmer
Usually I'm based on programming HAL in small uControllers, so please have a close look to my implementation.
It was just tested on up to date Linux Mint and Ubuntu.

Best regards and thanks for this great piece of software. I really enjoy to use it.

### CODE REVIEW

**Comment by csete** [comment]
Thanks for the submission. Currently, gqrx development is on hold until we find a new maintainer.

Note that your patch fails to build by Travis CI.

**Comment by ra1nb0w** [comment]
seen that the development is alive you can merge this great contribute :)

**Comment by argilo** [comment]
I had trouble pushing a rebased version of this pull request to @dh2wq's fork, so I'm continuing work in #864 instead.

**Comment by ra1nb0w** [comment]
I am maintaining an up-to-date version of this PR on my [experimental branch](https://github.com/ra1nb0w/gqrx/tree/experimental) that it is used on macports. Feel free to check.

**Pull request closed without merging**
