### PR TITLE
AM-Sync implemented as AM demod option

### PR DESCRIPTION
**Pull request by gat3way**
Hello,

Left the mode enums intact and implemented synchronous AM detector mode as a demod option, hope it's OK now

### CODE REVIEW

**Comment by csete** [comment]
Thanks for the update! I will do my best to review and test it in the coming weeks.

**Comment by gat3way** [comment]
I did some (kind of controversial) improvements, most notably we now filter before the PLL refout block and I tweaked the loop bandwidth and the filter cutoff a bit to have a much more stable PLL lock. The end result being we now have a noticeably better AM-Sync mode, this is a real improvement, just as it has to be. The end result being it considerably helps with selective fading and we have a much better result even with weak signals. On the negative side, users now have to tune very precisely, as larger offsets from station's carrier frequency will get the carrier off the filter and we also need much more CPU power to satisfy the filter. Users with slower CPUs may have issues with that. That said, ideally speaking probably two or more am-sync modes need to be introduced where we compromise between demodulated audio quality and CPU resources/tuning offset.

**Comment by kukabu** [comment]
I think it's a bad way. This way complicate the code for bookmarks and remote control.
with PR #462 way (AMS as mode)
- bookmark - must be works without any modification
- remote control - requires small changes in four functions

**Comment by csete** [comment]
Good points @kukabu, perhaps it's best to add it as a new mode. In that case we should add it to the end of the list to keep backwards compatibility.

**Comment by gat3way** [comment]
I am a bit confused, at the end we are doing that as a new mode or as a demod option?

**Comment by csete** [comment]
Sorry for the confusion @gat3way. I think it's best to add it as a new mode appending it to the end of the list, otherwise it will be difficult to integrate it with bookmarks and remote control. Is it OK with you?

**Comment by gat3way** [comment]
No problem, will do that in the following days.

**Comment by csete** [comment]
Great, thanks. There is no hurry from my part as it will still be a few weeks before I am up and running at my new place.

**Comment by csete** [comment]
It doesn't look like this will happen. Feel free to resubmit if you still wish to work on it.

**Pull request closed without merging**
