### PR TITLE
Cosmetic changes

### PR DESCRIPTION
**Pull request by Cat-Ion**
Addresses #438

### CODE REVIEW

**Comment by csete** [comment]
Good idea to improve readability of the code, but why not go all the way and replace that confusing if statement with a while loop? Also, the comment seems the opposite of what it should be, no?

I would also much prefer if the commits were squashed into one commit.

**Comment by Cat-Ion** [comment]
Replacing it with a while loop? I'm not sure I understand. Are you talking about the replacement for the modulo? But yes, the > should be replaced with <=, of course.

I... can try to do a force push to replace the commits? I've never done this before, but I'll try. Worst case we'll just close the PR and make a new one =P

**Comment by csete** [comment]
```
while (level < nLevels && tagEnd[level] > x)
    level++;
```
Easier to read, no?

I'm okay with a new pull request if it works out better. Would much prefer one commit rather than three for this.

**Comment by Cat-Ion** [comment]
Oh, you meant the for loop. Yeah, that's probably better.

**Comment by Cat-Ion** [comment]
The push worked! Hooray. :)

**Pull request merged**
