### PR TITLE
AppImage Generation, closes #707

### LINKED ISSUE #707: Gqrx AppImage does not run
The AppImage version of Gqrx crashes with `This application failed to start because it could not find or load the Qt platform plugin "xcb".` error printed on stdout.

This was already reported before as #667, but got closed afterwards. However the issue is still present.

By the way, Gqrx also needs _libnsl.so.1_ that is not bundled in the AppImage. It would be great if the Gqrx AppImage had all the needed libraries included so it would work out-of-box on most big distributions without the need to install any packages.

I am using fully updated Fedora 30 Workstation with default set of packages.

### PR DESCRIPTION
**Pull request by stdevPavelmc**
This adds a script to the repository to build the AppImage, see the coments from @csete here: https://github.com/csete/gqrx/issues/707#issuecomment-613338816 This closes #707

Read the comments on the script about configs and options, tested on Ubuntu trusty, bionic and focal locally
 
Cheers/73

### CODE REVIEW

**Comment by csete** [comment]
I tried the script but the issue reported in #707 remains for me. I suspect something is strange on my computer. So I am going to merge this PR, however, since I can not generate a working appimage, can you provide one of the latest 2.12.1 release? e.g. via https://www.filemail.com/

**Comment by csete** [comment]
Merged manually.

**Comment by stdevPavelmc** [comment]
This is the build for the v2.12.1 tag on the main repo

https://github.com/stdevPavelmc/gqrx/releases/download/untagged-e4100a7d2ca15ae1b126/Gqrx-continuous-x86_64.AppImage

**Comment by csete** [comment]
Thanks, I have added it to the release page.

**Pull request closed without merging**
