### PR TITLE
Improved noise blankers

### PR DESCRIPTION
**Pull request by gat3way**
PLEASE DO NOT MERGE!!!

I opened that pull request to start a discussion about this. I ported the LMS noise reduction and Spectral Noise Reduction algorithms from the wdsp library (it's GPL so there shouldn't be licensing issues).

The way they are implemented, they replace the current NB1 and NB2. I'd say both algorithms are much more advanced and powerful than what we currently have available in gqrx and after some tweaks it got close to the quality offered by sdrsharp's noise reduction. Please see the demo video I did:

https://www.youtube.com/watch?v=ISgfsq759wU

There are lots of reasons this should not get merged in its current form. First of all, it is invasive and changed the flowchart of nbrx receiver. The blankers are now applied post-demod (even though they take complex input, thus the stupid f2c/c2f blocks, I need to resolve this as it wastes precious CPU resources).

The settings to the algorithms are currently not exposed via the UI. The new NB1 has at least two settings that can be changed - gain and threshold (defaults should be fine, but better results can be achieved with some tweaking of course), the other one does not have anything that we can tweak at runtime (well there is a FFT size parameter and by increasing the bins number we can get even better quality at the expense of lots of CPU time, I left it at some sensible default - but that's something currently implemented in the constructor, it would take some time to make it dynamically tunnable if possible at all ).

From NB2's spectral noise reduction, we only implement the WDSP advised default gain and npe methods as they are performing better than the others anyway. Unfortunately this also requires a large (about 1MB) file with precalculated constants to be available (the file is named "calculus" and is committed under src/dsp). In the current code state, this file has to be in the current directory you run gqrx from, otherwise it would crash. Thus a mechanism to install it to a common location need to be implemented. Another possibility is to hardcode the values in an array (ugly and that would increase the binary size by 1MB, but still a possibility). 

There are lots of open questions with that pull request that need to be addressed and I honestly don't expect it to be merged in any form:) But still if you are interested, I guess with some efforts this can be made part of gqrx, lot of people (especially HF listeners like me) would find it useful.

P.S the code is still ugly and needs a cleanup, I will work on this in the following days.

### CODE REVIEW

**Comment by gat3way** [comment]
P.S actually I think this should be closed, as there are actually licensing conflicts, wdsp is GPLv2 and gqrx is Apache and I guess even if we don't use exactly the wdsp source, this would still count as a derivative work. Ah, for some reason I thought gqrx is also GPL...

**Comment by alexf91** [comment]
Gqrx is GPL. The Apache License only refers to widgets from the CTK project.

**Comment by gat3way** [comment]
That's great to hear.

**Comment by gat3way** [comment]
OK cleaned up lot of mess. The calculus file is not needed anymore, f2c/c2f blocks are gone.

**Comment by csete** [comment]
Hi,

Thanks for testing and submitting this. I think it is interesting and worth exploring.

One of my question was where this came from, but you mention that it is from WDSP. I am aware of WDSP but never really used so I want to ask: Could we use WDSP as an external library? I.e. leave the implementation there and only add GUI and wrapper code in gqrx?

If WDSP can be installed as a library by the user, gqrx can load it at runtime and enable the respective code. So it would not even be a build time dependency but loaded like a plugin. If you think this could work I can set up a dedicated branch we can play in.

I'm not convinced this noise reduction is direct replacement of the current one. One of the current ones are just for removing pulse type noise like electric fence and as I recall works quite all right. I need to take a look at the WDSP documents if they exists.

I am going to play with it a little over the coming the days to see how it works.

PS: You didn't remove the binary file ;-)

**Comment by gat3way** [comment]
That would be rather hard unless you switch from the gnuradio framework for the wdsp one. Using the high level wdsp API....I don't think so. They depend on their framework. Probably we can hack our way by setting up the structs they use and by calling directly the respective helper and work functions ourselves. But those expect fixed number of samples per run and the input and output formats are not what gnuradio can directly use (they always operate with complex streams where the complex values consist of two consecutive doubles - for real streams they discard every second value). So that would be even more hacky to use together with gnuradio than grabbing and modifying the code in question.

The current noise blankers actually do exist in WDSP as well (although their algorithm is not exactly the same but a bit more complex - the overall effect and input parameters are more or less the same - see the preemptive wideband noise blanker and the interpolating wideband noise blanker in the WDSP guide at https://github.com/TAPR/OpenHPSDR-wdsp/blob/master/WDSP%20Guide.pdf

Like the gqrx noise blankers, they operate on complex IQ data and they have configurable threshold. 

Good catch about the binary file, I am removing it now...

**Comment by csete** [comment]
OK, lets see where it goes.

**Comment by csete** [comment]
Here are two more demos:

AM: https://www.youtube.com/watch?v=30ccfgVVEaM
SSB: https://www.youtube.com/watch?v=DPaD4ek0LBA

**Comment by gat3way** [comment]
Looks nice :)

**Comment by gat3way** [comment]
Shall we proceed with merging that in gqrx? If yes - there is that important problem with integrating it with the UI layer (especially the parameters of NB1 and NB2). Here I have no idea on how to proceed really. 

Also the old NB algorithms should be still present I guess, replacing them is not that great idea. 

Also I found out there is an opensource general purpose SDR software, HPSDR that is built upon WDSP. I looked at their code and it turns out they use the "wideband" blankers (the ones in WDSP that work similarily to the current NB1/NB2 in gqrx) in a rather.....strange way. They apply them almost right after the SDR source so that they operate on the whole I/Q stream and affect the spectrum/waterfall displays as well apparently. Not sure if this is a good idea though, but probably good for easier tuning of the thresholds as you get visual feedback as well. This at the expense of CPU overhead for sure.

**Comment by csete** [comment]
I don't think you should expect this to be merged into gqrx master anytime soon for several reasons.

First, I need to have a proper understanding of what we are dealing with here before I can commit to any decision or to have an idea what this should be called or how it should appear in the GUI. I work on other projects now and have basically no time for gqrx, so it will take some time to process all this.

On the more practical side, credits, copyrights and references to original work should be in place before we commit the code. It might be a good idea not the replace the old NB functions but add a new noise reduction file. We can remove the old ones later.

At this point I am confused about what you mean with the various noise blankers. Where they are applied depends on their type and purpose. They can be wide band applied at the input, IF or audio. As I recall this new one is audio, which is partly why I don't think it can not replace our existing ones. There are many noise types that need tp be removed before they can affect the AGC, which is in the IF.

So, as you can see, we (or at least I) need time to understand what we are dealing with.

**Comment by gat3way** [comment]
Sorry for pushing and I understand your concerns. I have a suggesion but probably you've seen such an argument before - how about having an experimental branch? This way people would be encouraged to contribute while you can have your time on your other projects and only merge in the master when you decide stuff is mature enough and compliant?

The copyrights and credits part in that particular case are easy to handle as long as both projects stick to GPLv2. However it is exactly the project's ideological (plus the UI) realms which I am really lost into. So again, perhaps having an experimental branch is not that bad idea. I am sure lots of user contributions will eventually get there and this will only benefit the project.

**Comment by csete** [comment]
We get code into gqrx when it is ready. I sometimes create dedicated development branches, and this PR may indeed start in such a branch. However, thiecode will not get more exposure by being in branch versus being in a pull request here. In fact, quite the opposite.

My comment about license was not conceptual but referring to a specific problem. You replaced the code in the original noise blanker sources with new code, but left the copyright header untouched. Things like this have to be resolved before we put the code in gqrx repo.

**Comment by gat3way** [comment]
Fair enough. Meanwhile for the fun of it I've started an experimental branch to bring some features into gqrx. Many of them are quick hacks that need a lot of cleanup and polishing. Others contradict with the project philosophy (I know you guys aren't very keen on having decoders in gqrx for example). I don't expect most if not any of this to ever get merged into master and I am not going to submit pull requests for any of the changes made. Still I think it's worth and interesting working on something like this as a side project.

**Comment by csete** [comment]
> I know you guys aren't very keen on having decoders in gqrx for example

It depends on what "in gqrx" means... If it means coded inside gqrx like the AFSK decoder, then no. If it means having an interface to interact with external decoders, then yes, see issue #100.

**Comment by gat3way** [comment]
Yeah I've read that before. I kindly disagree though because I don't think a common interface can be designed so that users can have seamless operation in all cases. Sometimes it's pulseaudio that "glues" it all because the external decoder doesn't care about stdin/stdout (such as say fldigi). Sometimes yes piping stdin/stdout could be an option (say multimon-ng). Sometimes both aren't an option at all - like in e.g rtl_433's case. It just wants to operate on I/Q data and it does the demodulation itself, it doesn't like the idea of getting input from stdin which makes it impossible to easily tune to some signal while watching it on the waterfall (leave alone it supports only rtl-sdr hardware). Or another example (as in Issue #100) - DSD. It is hard to define such interface. It might output data from the MBE codec to the audio device and then the decoded frames on stdout. Pulseaudio could do the resampling and you would also get the stdout. But I am afraid there is just no standartized way to do that and people would have to fall back to manual configuration. And yes, I agree MBE is quite a bad problem with those patent issues.

**Comment by csete** [comment]
I never claimed this interface would solve everybody's problem once and for all. It would merely provide a clean and simple interface to use external decoders. Some decoders would work as is, some would require new interface.

Anyway, this is off topic here.

**Comment by spamcop** [comment]
I just want to thank gat3way for porting this, its a game changer in listening comfort.

**Comment by csete** [comment]
Doesn't look like this will happen.

**Comment by ulrichloose** [comment]
I've been using this great Noiseblanker for quite a while and I'm thrilled ... But now I've noticed that gqrx crashes if you accidentally set RAW I / Q. I don't need RAW I / Q, so I just set the entry to the same setting as Demod off. This is of course not correct ...

Maybe ra1nb0w could take another look at his code and fix it properly?

**Comment by ra1nb0w** [comment]
@ulrichloose you should paste the trace error from the console ...

**Pull request closed without merging**
