### PR TITLE
Google Turbo Colormaps

### PR DESCRIPTION
**Pull request by ckuethe**
https://ai.googleblog.com/2019/08/turbo-improved-rainbow-colormap-for.html

Inspired by something @devnulling said on twitter a while ago, this patch adds an implementation of "Turbo, An Improved Rainbow Colormap for Visualization"

turbo

### CODE REVIEW

**Comment by csete** [comment]
Thanks for the patch. This color map looks nice. It would be great to be able to switch between different color maps at runtime :)

**Comment by ckuethe** [comment]
I was afraid you would say that. Okay, I'll see if I can figure out a not too terrible way to allow for runtime color map selection.

**Comment by devnulling** [comment]
@ckuethe here are the color codes for a plasma color map, it'd be nice to have it as an option too :)

plasma


```
	m_ColorTbl[0].setRgb(12, 7, 134);
	m_ColorTbl[1].setRgb(16, 7, 135);
	m_ColorTbl[2].setRgb(19, 6, 137);
	m_ColorTbl[3].setRgb(21, 6, 138);
	m_ColorTbl[4].setRgb(24, 6, 139);
	m_ColorTbl[5].setRgb(27, 6, 140);
	m_ColorTbl[6].setRgb(29, 6, 141);
	m_ColorTbl[7].setRgb(31, 5, 142);
	m_ColorTbl[8].setRgb(33, 5, 143);
	m_ColorTbl[9].setRgb(35, 5, 144);
	m_ColorTbl[10].setRgb(37, 5, 145);
	m_ColorTbl[11].setRgb(39, 5, 146);
	m_ColorTbl[12].setRgb(41, 5, 147);
	m_ColorTbl[13].setRgb(43, 5, 148);
	m_ColorTbl[14].setRgb(45, 4, 148);
	m_ColorTbl[15].setRgb(47, 4, 149);
	m_ColorTbl[16].setRgb(49, 4, 150);
	m_ColorTbl[17].setRgb(51, 4, 151);
	m_ColorTbl[18].setRgb(52, 4, 152);
	m_ColorTbl[19].setRgb(54, 4, 152);
	m_ColorTbl[20].setRgb(56, 4, 153);
	m_ColorTbl[21].setRgb(58, 4, 154);
	m_ColorTbl[22].setRgb(59, 3, 154);
	m_ColorTbl[23].setRgb(61, 3, 155);
	m_ColorTbl[24].setRgb(63, 3, 156);
	m_ColorTbl[25].setRgb(64, 3, 156);
	m_ColorTbl[26].setRgb(66, 3, 157);
	m_ColorTbl[27].setRgb(68, 3, 158);
	m_ColorTbl[28].setRgb(69, 3, 158);
	m_ColorTbl[29].setRgb(71, 2, 159);
	m_ColorTbl[30].setRgb(73, 2, 159);
	m_ColorTbl[31].setRgb(74, 2, 160);
	m_ColorTbl[32].setRgb(76, 2, 161);
	m_ColorTbl[33].setRgb(78, 2, 161);
	m_ColorTbl[34].setRgb(79, 2, 162);
	m_ColorTbl[35].setRgb(81, 1, 162);
	m_ColorTbl[36].setRgb(82, 1, 163);
	m_ColorTbl[37].setRgb(84, 1, 163);
	m_ColorTbl[38].setRgb(86, 1, 163);
	m_ColorTbl[39].setRgb(87, 1, 164);
	m_ColorTbl[40].setRgb(89, 1, 164);
	m_ColorTbl[41].setRgb(90, 0, 165);
	m_ColorTbl[42].setRgb(92, 0, 165);
	m_ColorTbl[43].setRgb(94, 0, 165);
	m_ColorTbl[44].setRgb(95, 0, 166);
	m_ColorTbl[45].setRgb(97, 0, 166);
	m_ColorTbl[46].setRgb(98, 0, 166);
	m_ColorTbl[47].setRgb(100, 0, 167);
	m_ColorTbl[48].setRgb(101, 0, 167);
	m_ColorTbl[49].setRgb(103, 0, 167);
	m_ColorTbl[50].setRgb(104, 0, 167);
	m_ColorTbl[51].setRgb(106, 0, 167);
	m_ColorTbl[52].setRgb(108, 0, 168);
	m_ColorTbl[53].setRgb(109, 0, 168);
	m_ColorTbl[54].setRgb(111, 0, 168);
	m_ColorTbl[55].setRgb(112, 0, 168);
	m_ColorTbl[56].setRgb(114, 0, 168);
	m_ColorTbl[57].setRgb(115, 0, 168);
	m_ColorTbl[58].setRgb(117, 0, 168);
	m_ColorTbl[59].setRgb(118, 1, 168);
	m_ColorTbl[60].setRgb(120, 1, 168);
	m_ColorTbl[61].setRgb(121, 1, 168);
	m_ColorTbl[62].setRgb(123, 2, 168);
	m_ColorTbl[63].setRgb(124, 2, 167);
	m_ColorTbl[64].setRgb(126, 3, 167);
	m_ColorTbl[65].setRgb(127, 3, 167);
	m_ColorTbl[66].setRgb(129, 4, 167);
	m_ColorTbl[67].setRgb(130, 4, 167);
	m_ColorTbl[68].setRgb(132, 5, 166);
	m_ColorTbl[69].setRgb(133, 6, 166);
	m_ColorTbl[70].setRgb(134, 7, 166);
	m_ColorTbl[71].setRgb(136, 7, 165);
	m_ColorTbl[72].setRgb(137, 8, 165);
	m_ColorTbl[73].setRgb(139, 9, 164);
	m_ColorTbl[74].setRgb(140, 10, 164);
	m_ColorTbl[75].setRgb(142, 12, 164);
	m_ColorTbl[76].setRgb(143, 13, 163);
	m_ColorTbl[77].setRgb(144, 14, 163);
	m_ColorTbl[78].setRgb(146, 15, 162);
	m_ColorTbl[79].setRgb(147, 16, 161);
	m_ColorTbl[80].setRgb(149, 17, 161);
	m_ColorTbl[81].setRgb(150, 18, 160);
	m_ColorTbl[82].setRgb(151, 19, 160);
	m_ColorTbl[83].setRgb(153, 20, 159);
	m_ColorTbl[84].setRgb(154, 21, 158);
	m_ColorTbl[85].setRgb(155, 23, 158);
	m_ColorTbl[86].setRgb(157, 24, 157);
	m_ColorTbl[87].setRgb(158, 25, 156);
	m_ColorTbl[88].setRgb(159, 26, 155);
	m_ColorTbl[89].setRgb(160, 27, 155);
	m_ColorTbl[90].setRgb(162, 28, 154);
	m_ColorTbl[91].setRgb(163, 29, 153);
	m_ColorTbl[92].setRgb(164, 30, 152);
	m_ColorTbl[93].setRgb(165, 31, 151);
	m_ColorTbl[94].setRgb(167, 33, 151);
	m_ColorTbl[95].setRgb(168, 34, 150);
	m_ColorTbl[96].setRgb(169, 35, 149);
	m_ColorTbl[97].setRgb(170, 36, 148);
	m_ColorTbl[98].setRgb(172, 37, 147);
	m_ColorTbl[99].setRgb(173, 38, 146);
	m_ColorTbl[100].setRgb(174, 39, 145);
	m_ColorTbl[101].setRgb(175, 40, 144);
	m_ColorTbl[102].setRgb(176, 42, 143);
	m_ColorTbl[103].setRgb(177, 43, 143);
	m_ColorTbl[104].setRgb(178, 44, 142);
	m_ColorTbl[105].setRgb(180, 45, 141);
	m_ColorTbl[106].setRgb(181, 46, 140);
	m_ColorTbl[107].setRgb(182, 47, 139);
	m_ColorTbl[108].setRgb(183, 48, 138);
	m_ColorTbl[109].setRgb(184, 50, 137);
	m_ColorTbl[110].setRgb(185, 51, 136);
	m_ColorTbl[111].setRgb(186, 52, 135);
	m_ColorTbl[112].setRgb(187, 53, 134);
	m_ColorTbl[113].setRgb(188, 54, 133);
	m_ColorTbl[114].setRgb(189, 55, 132);
	m_ColorTbl[115].setRgb(190, 56, 131);
	m_ColorTbl[116].setRgb(191, 57, 130);
	m_ColorTbl[117].setRgb(192, 59, 129);
	m_ColorTbl[118].setRgb(193, 60, 128);
	m_ColorTbl[119].setRgb(194, 61, 128);
	m_ColorTbl[120].setRgb(195, 62, 127);
	m_ColorTbl[121].setRgb(196, 63, 126);
	m_ColorTbl[122].setRgb(197, 64, 125);
	m_ColorTbl[123].setRgb(198, 65, 124);
	m_ColorTbl[124].setRgb(199, 66, 123);
	m_ColorTbl[125].setRgb(200, 68, 122);
	m_ColorTbl[126].setRgb(201, 69, 121);
	m_ColorTbl[127].setRgb(202, 70, 120);
	m_ColorTbl[128].setRgb(203, 71, 119);
	m_ColorTbl[129].setRgb(204, 72, 118);
	m_ColorTbl[130].setRgb(205, 73, 117);
	m_ColorTbl[131].setRgb(206, 74, 117);
	m_ColorTbl[132].setRgb(207, 75, 116);
	m_ColorTbl[133].setRgb(208, 77, 115);
	m_ColorTbl[134].setRgb(209, 78, 114);
	m_ColorTbl[135].setRgb(209, 79, 113);
	m_ColorTbl[136].setRgb(210, 80, 112);
	m_ColorTbl[137].setRgb(211, 81, 111);
	m_ColorTbl[138].setRgb(212, 82, 110);
	m_ColorTbl[139].setRgb(213, 83, 109);
	m_ColorTbl[140].setRgb(214, 85, 109);
	m_ColorTbl[141].setRgb(215, 86, 108);
	m_ColorTbl[142].setRgb(215, 87, 107);
	m_ColorTbl[143].setRgb(216, 88, 106);
	m_ColorTbl[144].setRgb(217, 89, 105);
	m_ColorTbl[145].setRgb(218, 90, 104);
	m_ColorTbl[146].setRgb(219, 91, 103);
	m_ColorTbl[147].setRgb(220, 93, 102);
	m_ColorTbl[148].setRgb(220, 94, 102);
	m_ColorTbl[149].setRgb(221, 95, 101);
	m_ColorTbl[150].setRgb(222, 96, 100);
	m_ColorTbl[151].setRgb(223, 97, 99);
	m_ColorTbl[152].setRgb(223, 98, 98);
	m_ColorTbl[153].setRgb(224, 100, 97);
	m_ColorTbl[154].setRgb(225, 101, 96);
	m_ColorTbl[155].setRgb(226, 102, 96);
	m_ColorTbl[156].setRgb(227, 103, 95);
	m_ColorTbl[157].setRgb(227, 104, 94);
	m_ColorTbl[158].setRgb(228, 106, 93);
	m_ColorTbl[159].setRgb(229, 107, 92);
	m_ColorTbl[160].setRgb(229, 108, 91);
	m_ColorTbl[161].setRgb(230, 109, 90);
	m_ColorTbl[162].setRgb(231, 110, 90);
	m_ColorTbl[163].setRgb(232, 112, 89);
	m_ColorTbl[164].setRgb(232, 113, 88);
	m_ColorTbl[165].setRgb(233, 114, 87);
	m_ColorTbl[166].setRgb(234, 115, 86);
	m_ColorTbl[167].setRgb(234, 116, 85);
	m_ColorTbl[168].setRgb(235, 118, 84);
	m_ColorTbl[169].setRgb(236, 119, 84);
	m_ColorTbl[170].setRgb(236, 120, 83);
	m_ColorTbl[171].setRgb(237, 121, 82);
	m_ColorTbl[172].setRgb(237, 123, 81);
	m_ColorTbl[173].setRgb(238, 124, 80);
	m_ColorTbl[174].setRgb(239, 125, 79);
	m_ColorTbl[175].setRgb(239, 126, 78);
	m_ColorTbl[176].setRgb(240, 128, 77);
	m_ColorTbl[177].setRgb(240, 129, 77);
	m_ColorTbl[178].setRgb(241, 130, 76);
	m_ColorTbl[179].setRgb(242, 132, 75);
	m_ColorTbl[180].setRgb(242, 133, 74);
	m_ColorTbl[181].setRgb(243, 134, 73);
	m_ColorTbl[182].setRgb(243, 135, 72);
	m_ColorTbl[183].setRgb(244, 137, 71);
	m_ColorTbl[184].setRgb(244, 138, 71);
	m_ColorTbl[185].setRgb(245, 139, 70);
	m_ColorTbl[186].setRgb(245, 141, 69);
	m_ColorTbl[187].setRgb(246, 142, 68);
	m_ColorTbl[188].setRgb(246, 143, 67);
	m_ColorTbl[189].setRgb(246, 145, 66);
	m_ColorTbl[190].setRgb(247, 146, 65);
	m_ColorTbl[191].setRgb(247, 147, 65);
	m_ColorTbl[192].setRgb(248, 149, 64);
	m_ColorTbl[193].setRgb(248, 150, 63);
	m_ColorTbl[194].setRgb(248, 152, 62);
	m_ColorTbl[195].setRgb(249, 153, 61);
	m_ColorTbl[196].setRgb(249, 154, 60);
	m_ColorTbl[197].setRgb(250, 156, 59);
	m_ColorTbl[198].setRgb(250, 157, 58);
	m_ColorTbl[199].setRgb(250, 159, 58);
	m_ColorTbl[200].setRgb(250, 160, 57);
	m_ColorTbl[201].setRgb(251, 162, 56);
	m_ColorTbl[202].setRgb(251, 163, 55);
	m_ColorTbl[203].setRgb(251, 164, 54);
	m_ColorTbl[204].setRgb(252, 166, 53);
	m_ColorTbl[205].setRgb(252, 167, 53);
	m_ColorTbl[206].setRgb(252, 169, 52);
	m_ColorTbl[207].setRgb(252, 170, 51);
	m_ColorTbl[208].setRgb(252, 172, 50);
	m_ColorTbl[209].setRgb(252, 173, 49);
	m_ColorTbl[210].setRgb(253, 175, 49);
	m_ColorTbl[211].setRgb(253, 176, 48);
	m_ColorTbl[212].setRgb(253, 178, 47);
	m_ColorTbl[213].setRgb(253, 179, 46);
	m_ColorTbl[214].setRgb(253, 181, 45);
	m_ColorTbl[215].setRgb(253, 182, 45);
	m_ColorTbl[216].setRgb(253, 184, 44);
	m_ColorTbl[217].setRgb(253, 185, 43);
	m_ColorTbl[218].setRgb(253, 187, 43);
	m_ColorTbl[219].setRgb(253, 188, 42);
	m_ColorTbl[220].setRgb(253, 190, 41);
	m_ColorTbl[221].setRgb(253, 192, 41);
	m_ColorTbl[222].setRgb(253, 193, 40);
	m_ColorTbl[223].setRgb(253, 195, 40);
	m_ColorTbl[224].setRgb(253, 196, 39);
	m_ColorTbl[225].setRgb(253, 198, 38);
	m_ColorTbl[226].setRgb(252, 199, 38);
	m_ColorTbl[227].setRgb(252, 201, 38);
	m_ColorTbl[228].setRgb(252, 203, 37);
	m_ColorTbl[229].setRgb(252, 204, 37);
	m_ColorTbl[230].setRgb(252, 206, 37);
	m_ColorTbl[231].setRgb(251, 208, 36);
	m_ColorTbl[232].setRgb(251, 209, 36);
	m_ColorTbl[233].setRgb(251, 211, 36);
	m_ColorTbl[234].setRgb(250, 213, 36);
	m_ColorTbl[235].setRgb(250, 214, 36);
	m_ColorTbl[236].setRgb(250, 216, 36);
	m_ColorTbl[237].setRgb(249, 217, 36);
	m_ColorTbl[238].setRgb(249, 219, 36);
	m_ColorTbl[239].setRgb(248, 221, 36);
	m_ColorTbl[240].setRgb(248, 223, 36);
	m_ColorTbl[241].setRgb(247, 224, 36);
	m_ColorTbl[242].setRgb(247, 226, 37);
	m_ColorTbl[243].setRgb(246, 228, 37);
	m_ColorTbl[244].setRgb(246, 229, 37);
	m_ColorTbl[245].setRgb(245, 231, 38);
	m_ColorTbl[246].setRgb(245, 233, 38);
	m_ColorTbl[247].setRgb(244, 234, 38);
	m_ColorTbl[248].setRgb(243, 236, 38);
	m_ColorTbl[249].setRgb(243, 238, 38);
	m_ColorTbl[250].setRgb(242, 240, 38);
	m_ColorTbl[251].setRgb(242, 241, 38);
	m_ColorTbl[252].setRgb(241, 243, 38);
	m_ColorTbl[253].setRgb(240, 245, 37);
	m_ColorTbl[254].setRgb(240, 246, 35);
	m_ColorTbl[255].setRgb(239, 248, 33);
```

**Comment by ckuethe** [comment]
Mkay. I'll give that some more thought.

**Comment by csete** [comment]
@ckuethe, @devnulling,

Thanks for the tables. Try git now ;)

**Pull request closed without merging**
