### PR TITLE
Read and write squelch via remote control

### PR DESCRIPTION
**Pull request by alexf91**
Allows read and write of squelch level over TCP.
I also rewrote some of the remote control code to allow spaces in commands.
#282

### CODE REVIEW

**Comment by csete** [comment]
Please never mix several topics into one pull request. This way it is difficult to make a proper review.

The QString based command processing is likely to be much slower that the current char based processing. So I am going to need a very good reason to even consider that change.

So, please submit the squelch in its own pull request. When you do, please also update the resources/remote-control.txt file. I assume the command is compatible with the hamlib rigctld interface.

**Comment by alexf91** [comment]
Ok, I'll split it.
I changed the chars to QString because it's easier to handle parameters for commands.
QStrings are already used in the modeStrToInt and intToModeStr functions, so I thought it would be okay to use them.

**Comment by csete** [comment]
Well, maybe I am overreacting. I didn't take a thorough look at it. We can leave it like this and I can take a closer look at it in a few days or next week as I am too busy at the moment.

I would still like to have the remote-control.txt file updated.

**Comment by csete** [comment]
Ok, I had a chance to review and test it and I think it is fine. However, I would kindly ask you to make one last change, which is to allow the command "l" without any option. I.e. the command "l" without STRENGTH or SQL parameter would default to STRENGTH and that way keep backward compatibility with existing applications.

**Comment by csete** [comment]
Thanks.

**Pull request merged**
